### ISSUE TITLE
Moving project

### ISSUE THREAD

**Issue by mmajcica** [DotNetAnalyzers/UseConditionalOperatorAnalyzer#1]
Hi Dave,

first of all, thank you for the nice example and the explanation in your post.
I was wondering if you will be willing to move this project under https://github.com/DotNetAnalyzers so we can keep the code under the common root, which makes it easier to find.
What do you think?

Thanks

**Comment by davefancher** [comment]
I'd be perfectly happy to move it over. I debated putting it there originally but given some of the early discussion about the analyzers project not including analyzers/fix providers that were largely opinion-based like my preference for the conditional operator over if..else statements, I didn't know whether it would be appropriate.

I've never moved a project around on Github before. Is there something I can use to make it an easy transition or would it be better to fork the analyzers project and submit a pull request?

**Comment by mmajcica** [comment]
That's good to hear.

Unfortunately I never moved anything around Github, so I'm at the same point as you. Maybe @sharwell can help us with this?

Cheers

**Comment by sharwell** [comment]
I can move it if you make me a collaborator on this project (with owner or admin access if it asks you). After the move, I'll invite you to the DotNetAnalyzers organization with owner rights to the relocated repository.

**Comment by davefancher** [comment]
Sam: You should now be a collaborator. Feel free to transfer the repo.

**Comment by sharwell** [comment]
Hi Dave,

It turns out I can only transfer the repository from organization to organization, not from user to organization. I granted you admin access to the organization **DotNetAnalyzersStaging**. You need to transfer the repository from your account to that organization, and then I will transfer it from that organization to **DotNetAnalyzers** and set up the permissions.

**Comment by davefancher** [comment]
It looks like the repo transferred successfully

**Comment by sharwell** [comment]
It did. :+1:
